AllCops:
  DisplayCopNames: true
  Exclude:
   - 'bin/*'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'
   - 'spec/dummy/**/*'
  Include:
    - 'lib/tasks/**/*'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Guardfile'
  TargetRubyVersion: 2.2
Documentation:
  Enabled: false
Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**'
Metrics/BlockLength:
  Exclude:
    - config/environments/production.rb
    - '**/*_spec.rb'
    - 'spec/support/shared_examples/**'
    - '**/factories/**/*'
    - 'vendor/**/*'
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**'
Metrics/ModuleLength:
  Exclude:
    - '**/*_spec.rb'
    - 'spec/support/shared_examples/**'
Naming/UncommunicativeMethodParamName:
  Enabled: false
Lint/Debugger:
  Enabled: false
Lint/DefEndAlignment:
  AutoCorrect: true
Lint/EndAlignment:
  AutoCorrect: true
Lint/AmbiguousBlockAssociation:
  Exclude:
   - '**/*_spec.rb'
   - 'spec/support/shared_examples/**'
Rails:
  Enabled: true
Rails/ActiveRecordAliases:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Rails/Output:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/DateTime:
  Enabled: false
